import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import AuthProvider from '@/components/AuthProvider'
import './globals.css'
import React from 'react'

// const playfair = Playfair_Display({subsets:['latin']})
const poppins = Poppins({subsets:['latin'], weight:['300', '400']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,

}: {
  children: React.ReactNode,

}) {

  return (
    <html lang="en">
      <body className={poppins.className} >
        <AuthProvider>
          {children}
        </AuthProvider>
    
      </body>
    </html>
  )
}
